version: "3.9"

volumes:
  pgdb: {}
  deps: {}
  build: {}
  node_modules: {}

services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - deps:/app/deps
      - build:/app/_build
      - node_modules:/app/assets/node_modules
    links:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:13-alpine
    volumes:
      - ./lib:/app/lib
      - pgdb:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
